spring:
  config:
    activate:
      # 개발 환경
      on-profile: develop

  datasource:
    url: ${DEVELOP_DB_URL}
    username: ${DEVELOP_DB_USERNAME}
    password: ${DEVELOP_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_OAUTH_CLIENT_ID}
            client-secret: ${GITHUB_OAUTH_CLIENT_SECRET}
            redirect-uri: ${OAUTH_REDIRECT_URI}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  frontend:
    url: ${FRONTEND_URL}

aws:
  s3:
    bucket: ${AWS_S3_BUCKET_NAME}
  region: ${AWS_REGION}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

firebase:
  config:
    path: ${FIREBASE_CONFIG_PATH}
