spring:
  config:
    activate:
      # 운영 환경
      on-profile: default

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

aws:
  s3:
    bucket: ${AWS_S3_BUKET_NAME}
  region: ${AWS_REGION}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

---

spring:
  config:
    activate:
      # 개발 환경
      on-profile: develop

  datasource:
    url: ${DEVELOP_DB_URL}
    username: ${DEVELOP_DB_USERNAME}
    password: ${DEVELOP_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_OAUTH_CLIENT_ID}
            client-secret: ${GITHUB_OAUTH_CLIENT_SECRET}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  frontend:
    url: http://localhost:5173

aws:
  s3:
    bucket: ${AWS_S3_BUKET_NAME}
  region: ${AWS_REGION}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

---
spring:
  config:
    activate:
      # 테스트 환경
      on-profile: test
  datasource:
    url: jdbc:h2:mem:database-test

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

  sql:
    init:
      mode: always
      data-locations:

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: test-client-id
            client-secret: test-client-secret

  h2:
    console:
      enabled: true

app:
  frontend:
    url: http://localhost:5173

aws:
  s3:
    bucket: test_aws_s3_buket_name
  region: ap-northeast-2
  credentials:
    access-key: test_aws_access_key
    secret-key: test_aws_secret_key
