spring:
  config:
    activate:
      # 운영 환경
      on-profile: default

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # spring jpa 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

---

spring:
  config:
    activate:
      # 개발 환경
      on-profile: develop

  datasource:
    url: ${DEVELOP_DB_URL}
    username: ${DEVELOP_DB_USERNAME}
    password: ${DEVELOP_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    # spring jpa 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liOpSuzzWVeB081T
            client-secret: d8ac3bccba7e1c9e72517bbdbac9818bc3b415d4

---

spring:
  config:
    activate:
      # 테스트 환경
      on-profile: test
  h2:
    console:
      enabled: true
      path: /h2-console-test
  datasource:
    url: jdbc:h2:mem:database-test
